### ISSUE TITLE
Add new blocks below the current group of blocks instead of at 0,0

### ISSUE THREAD

**Issue by cousincuey** [RITAccess/blockly#32]
Find the bottom most block and add the menu block below it that way blocks aren't overlapping

**Comment by MaryS94** [comment]
Statements are now automatically connected when added so they don't stack on top of each other. If a block cannot stand alone, then the user will be alerted audibly
that the block needs to be connected to another block. Statement blocks(if, while etc)
and function blocks will stand alone. Because functions cannot be
connected to statements, the function will be placed directly below the
last statement. If another statement is added afterwards, it will be
placed below the function and more statements will auto connect to the bottom statement.
