### ISSUE TITLE
Comments in blockly for jumping around in the code

### ISSUE THREAD

**Issue by cousincuey** [RITAccess/blockly#4]

**Comment by amber-libby** [comment]
Comments will be shown in a box on the side. Listed in an order where the top of the workspace down is the order of the comments. Each comment will have a location that will be linked upon reference.

**Comment by amber-libby** [comment]
Comments are shown in a div on the interface. They are named accordingly to the navigation. Comments are gathered by using the XML document created from what is on the blockly workspace. Comments are not yet linked to any location.

**Comment by amber-libby** [comment]
Comments are linked to their respective block by using a hotkey (currently g). As well as Blocks will link over to their respective comments (using hotkey g as well). There is an error if you place a block on the workspace and then tab all the way through to the toolbox and click the hotkey g. We don't see this being an issue because we are not planning to be able to tab all the way through to the toolbox.
